# Permalinks
permalink:           pretty

# Exclude future-dated posts until their date arrives (rebuilt daily via cron)
future:              false

# Timezone
timezone:            Australia/Brisbane

# Setup
title:               Tim Neilen
url:                 https://tim.neilen.com.au
shorturl:            tim.neilen.com.au
paginate:            50

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Tim Neilen
  url:               https://neilen.com.au
  email:             tim@neilen.com.au

# Custom vars
version:             1.0.0
github:
  repo:              https://github.com/teejayen/tim.neilen.com.au
analytics_id:        G-RLZS4VJSCX

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-gist

# Pages
pages_list:          {'Now':'/now','Books':'/books','Quotes':'/quotes','Cartography':'/cartography'}